In [1]:
import numpy as np

print("hello")


hello


In [2]:
arr1=np.array([[1,2,3],[1,3,4],[7,8,9]])
print(arr1)

[[1 2 3]
 [1 3 4]
 [7 8 9]]


In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory




In [4]:
"""
to create a 3x3 matrix with values ranging from 2 to 10
Name:- Bavarva Malay 
Enrollment:-216270307085
"""

import numpy as np

h = np.random.randint(2, 10,(3, 3))
print("3*3 matrix \n\n", h)




3*3 matrix 

 [[9 9 3]
 [9 2 8]
 [8 7 4]]


In [5]:
"""
to append values at the end of an array
Name:- Bavarva Malay 
Enrollment:-216270307085
"""

import numpy as np

arr=np.array([1,2,3])
print("\nBefore appending")
print(arr)
new_arr=np.append(arr,4)
print("After appending to last")
print(new_arr)





Before appending
[1 2 3]
After appending to last
[1 2 3 4]


In [6]:
"""
to create another shape from an array without changing its data (3*2 to 2*3)
Name:- Bavarva Malay 
Enrollment:-216270307085
"""

import numpy as np

print("3*2 array")
arr=np.array(([1,2],[3,4],[5,6]))
print(arr,"\n")

print("after changing its shape from 3*2 to 2*3\n")
new_arr=arr.reshape(2,3)
print(new_arr)





3*2 array
[[1 2]
 [3 4]
 [5 6]] 

after changing its shape from 3*2 to 2*3

[[1 2 3]
 [4 5 6]]


In [7]:
"""
practical 3
to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the 
original orde
Name:- Bavarva Malay 
Enrollment:-216270307085

"""

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(arr)
arr1,arr2,arr3 = np.split(arr,[2,6])
print(arr1)
print(arr2)
print(arr3)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1 2]
[3 4 5 6]
[ 7  8  9 10 11 12 13 14]


In [8]:
"""
practical 3
to stack arrays horizontally (column wise)
Name:- Bavarva Malay 
Enrollment:-216270307085

"""
import numpy as np

arr1 = np.array([[1,2,3],
            [4,5,6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
print( arr1)
print( arr2)


arr3 = np.hstack([arr1, arr2])
print("\nstack arrays horizontally (column wise): \n", arr3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

stack arrays horizontally (column wise): 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [9]:
"""
practical 4
to add, subtract, multiply, divide arguments element-wise
original orde
Name:- Bavarva Malay 
Enrollment:-216270307085
"""


arr=np.array([1,2,3,4])
print("Addition")
print(np.add(arr,2),"\n")

arr=np.array([1,2,3,4])
print("subtract")
print(np.subtract(arr,2),"\n")

arr=np.array([1,2,3,4])
print("divide")
print(np.divide(arr,2),"\n")

arr=np.array([1,2,3,4])
print("multiply")
print(np.multiply(arr,2),"\n")





Addition
[3 4 5 6] 

subtract
[-1  0  1  2] 

divide
[0.5 1.  1.5 2. ] 

multiply
[2 4 6 8] 



In [10]:
"""
practical 4
to round elements of the array to the nearest integer
Name:- Bavarva Malay 
Enrollment:-216270307085
"""

arr=np.array([1,2,3,4.5,5.6,3.4])
print("before round the array")
print(arr,"\n")

print("after round the array")
print(np.round(arr),"\n")


before round the array
[1.  2.  3.  4.5 5.6 3.4] 

after round the array
[1. 2. 3. 4. 6. 3.] 



In [11]:
"""
practical 4
to calculate mean across dimension, in a 2D numpy array
Name:- Bavarva Malay 
Enrollment:-216270307085
"""

arr=np.array([[1,2,3],[4,5,6]])
print(arr,"\n")

print("calculated mean")
print(np.mean(arr))

[[1 2 3]
 [4 5 6]] 

calculated mean
3.5
